branch-defaults:
  lesson-1:
    environment: skillbrain-env
environment-defaults:
  skillbrain-env:
    branch: null
    repository: null
global:
  application_name: skillbrain-app
  default_ec2_keyname: dani-test-key
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
